// Generated by gencpp from file drone_control/ModeResponse.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROL_MESSAGE_MODERESPONSE_H
#define DRONE_CONTROL_MESSAGE_MODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_control
{
template <class ContainerAllocator>
struct ModeResponse_
{
  typedef ModeResponse_<ContainerAllocator> Type;

  ModeResponse_()
    : srv_rep(false)  {
    }
  ModeResponse_(const ContainerAllocator& _alloc)
    : srv_rep(false)  {
  (void)_alloc;
    }



   typedef uint8_t _srv_rep_type;
  _srv_rep_type srv_rep;





  typedef boost::shared_ptr< ::drone_control::ModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_control::ModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModeResponse_

typedef ::drone_control::ModeResponse_<std::allocator<void> > ModeResponse;

typedef boost::shared_ptr< ::drone_control::ModeResponse > ModeResponsePtr;
typedef boost::shared_ptr< ::drone_control::ModeResponse const> ModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_control::ModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_control::ModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drone_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drone_control::ModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_control::ModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_control::ModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_control::ModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_control::ModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_control::ModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_control::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79440998869b8fba9398bb17de2f8409";
  }

  static const char* value(const ::drone_control::ModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79440998869b8fbaULL;
  static const uint64_t static_value2 = 0x9398bb17de2f8409ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_control::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_control/ModeResponse";
  }

  static const char* value(const ::drone_control::ModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_control::ModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool srv_rep\n\
\n\
";
  }

  static const char* value(const ::drone_control::ModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_control::ModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.srv_rep);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_control::ModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_control::ModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "srv_rep: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.srv_rep);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_CONTROL_MESSAGE_MODERESPONSE_H
