// Generated by gencpp from file drone_control/Mode.msg
// DO NOT EDIT!


#ifndef DRONE_CONTROL_MESSAGE_MODE_H
#define DRONE_CONTROL_MESSAGE_MODE_H

#include <ros/service_traits.h>


#include <drone_control/ModeRequest.h>
#include <drone_control/ModeResponse.h>


namespace drone_control
{

struct Mode
{

typedef ModeRequest Request;
typedef ModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Mode
} // namespace drone_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_control::Mode > {
  static const char* value()
  {
    return "79440998869b8fba9398bb17de2f8409";
  }

  static const char* value(const ::drone_control::Mode&) { return value(); }
};

template<>
struct DataType< ::drone_control::Mode > {
  static const char* value()
  {
    return "drone_control/Mode";
  }

  static const char* value(const ::drone_control::Mode&) { return value(); }
};


// service_traits::MD5Sum< ::drone_control::ModeRequest> should match 
// service_traits::MD5Sum< ::drone_control::Mode > 
template<>
struct MD5Sum< ::drone_control::ModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_control::Mode >::value();
  }
  static const char* value(const ::drone_control::ModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_control::ModeRequest> should match 
// service_traits::DataType< ::drone_control::Mode > 
template<>
struct DataType< ::drone_control::ModeRequest>
{
  static const char* value()
  {
    return DataType< ::drone_control::Mode >::value();
  }
  static const char* value(const ::drone_control::ModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_control::ModeResponse> should match 
// service_traits::MD5Sum< ::drone_control::Mode > 
template<>
struct MD5Sum< ::drone_control::ModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_control::Mode >::value();
  }
  static const char* value(const ::drone_control::ModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_control::ModeResponse> should match 
// service_traits::DataType< ::drone_control::Mode > 
template<>
struct DataType< ::drone_control::ModeResponse>
{
  static const char* value()
  {
    return DataType< ::drone_control::Mode >::value();
  }
  static const char* value(const ::drone_control::ModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_CONTROL_MESSAGE_MODE_H
